[package]
name = "day18"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = { workspace = true}
itertools = { workspace = true}
rayon = { workspace = true}
euclid = { workspace = true }
image = { workspace = true }
